CREATE TABLE games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    platform VARCHAR(255) NOT NULL,
    update_number VARCHAR(50),
    format VARCHAR(50),
    is_physical BOOLEAN DEFAULT FALSE,
    serial_number VARCHAR(255),
    storage_location VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);